before_script:
  - python -V # Print out python version for debugging

stages:
  - test

test-python-2.7:
  image: python:2.7
  stage: test
  script:
    - echo "Running tests"
    - python -m unittest discover -s "tests/"

test-python-3.5:
  image: python:3.5
  stage: test
  script:
    - echo "Running tests"
    - python -m unittest discover -s "tests/"

test-python-3.6:
  image: python:3.6
  stage: test
  script:
    - echo "Running tests"
    - python -m unittest discover -s "tests/"

test-python-3.7:
  image: python:3.7
  stage: test
  script:
    - echo "Running tests"
    - python -m unittest discover -s "tests/"

test-python-3.8:
  image: python:3.8
  stage: test
  script:
    - echo "Running tests"
    - python -m unittest discover -s "tests/"

test-python-latest:
  image: python:latest
  stage: test
  script:
    - echo "Running tests"
    - python -m unittest discover -s "tests/"